### ISSUE TITLE
Include Determinant check for mesh quality

### ISSUE THREAD

**Issue by florianwechsung** [fireshape/fireshape#6]

**Comment by APaganini** [comment]
And then modify `examples/pipe_main.py` and `test_volumeconstraint.py` (the latter fails for `MultiGridControl` with `ElasticityInnerProduct`)

**Comment by APaganini** [comment]
This can be sorted out using trust-region algorithms

**Comment by APaganini** [comment]
This can be sorted by adding a line in the objective function and returning nans.
It's up to the user's discretion whether to do it or not (because it depends on the
optimization algorithm used).
